Add category to .desktop file
vifino/vifino-overlay pull request #66
Opened 2022-03-27 17:50 UTC by ran-dall

Currently, once the ebuild has emerged, the installation will put the application in 'Lost & Found' (while using KDE) due to the fact that the .desktop doesn't have a specified category. This fixes the .desktop file.

2022-03-27 17:52 UTC, ran-dall commented
@vifino I also think that `default` (in `src_prepare`) should be executed after the modifications are done to the `.desktop` file.

2022-03-27 17:59 UTC, ran-dall commented
I also made a PR to upstream, as the problem comes from upstream...however, I don't know how fast they'll be to merge it. https://github.com/openrazer/openrazer/pull/1781

2022-03-27 19:47 UTC, vifino commented
Hey @ran-dall , this generally looks good to me! I think it'd be nice to have the user patches apply after the category patch. I'd love to get a quick commit from you that switches the order in this PR, I can merge that in one go then. :)

2022-03-27 19:48 UTC, vifino requested changes

2022-03-27 19:48 UTC, vifino commented on app-misc/openrazer/openrazer-3.2.0.ebuild
> +	sed -i '/^Icon=*/a Categories=System;HardwareSettings;' \
Nice use of sed! :)

2022-03-27 19:48 UTC, vifino commented on app-misc/openrazer/openrazer-3.2.0.ebuild
>  	default
Please change the order so that `default` is run after the patching of the `.desktop`.

2022-04-02 15:52 UTC, ran-dall commented
@vifino Sorry for it taking me a minute to update.

Should I also update `openrazer-9999.ebuild` and maybe the previous `.ebuilds` as well for OpenRazer?

2022-04-02 16:24 UTC, vifino commented
> @vifino Sorry for it taking me a minute to update.
Hey, don't worry about that at all! :)
> 
> Should I also update `openrazer-9999.ebuild` and maybe the previous `.ebuilds` as well for OpenRazer?

Updating the `9999` one sounds good to me, but I don't think it's necessary to update the old ones.

Thank you!

2022-04-02 16:45 UTC, ran-dall commented
@vifino That should do it! 😁

2022-04-02 16:50 UTC, vifino approved these changes

2022-04-02 16:50 UTC, merged

2022-04-02 16:50 UTC, vifino commented
And so it was merged! Thanks again! :)

2022-04-08 18:05 UTC, ran-dall commented
@vifino Hey man, if you don't mind, please take a look at my comment (https://github.com/openrazer/openrazer/pull/1781#issuecomment-1093138574). I think that perhaps we can benefit from a bit of clarification for OpenRC users that they need to move the `.desktop` file into `/etc/xdg/autostart`.